variables:
  IMAGE_NAME: shinjan7/collabrative_notepad
    
  APP_TAG : app
  NGINX_TAG : nginx

stages:
  - test
  - build


run_tests:
  stage: test
  image: python:3.10
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest tests/


build_image:
  stage: build
  image: docker:28.2.2

  services:
    - docker:28.2.2-dind
  variables:
      DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
      
  script:
  # Build images
    - docker build -t $IMAGE_NAME:$APP_TAG .
    - docker build -t $IMAGE_NAME:$NGINX_TAG ./nginx
    
     # Push both images
    - docker push $IMAGE_NAME:$APP_TAG 
    - docker push $IMAGE_NAME:$NGINX_TAG





