version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - notepad

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "8080:80"
    depends_on:
      - flask
    networks:
      - notepad

networks:
  notepad:
    external: true
