version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: collaborative-notepad
    ports:
      - "5000:5000"
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - flask
    restart: always
