version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    expose:
      - "5000"
    
    # networks:
    #   - notepad

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - flask
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # networks:
    #   - notepad

# networks:
#   notepad:
#     external: true
