global:
  scrape_interval: 15s

scrape_configs:
  - job_name: collaborative-notepad-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - collaborative-notepad-backend:8000
