name: Keep Alive
on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl my site
        run: curl -s https://collaborative-notepad-1.onrender.com/> /dev/null
